site_name: Deep Mux
site_description: Deep Mux documentation

repo_name: Deep-Mux
repo_url: https://github.com/Deep-Mux/deepmux-python

copyright: Copyright &copy; 2020 DeepMux

nav:
  - Overview: index.md
  - Details: details.md
  - FAQ: faq.md
  - 'Client Libraries':
    - 'Python': client-libraries/python.md
theme:
  name: material
  palette:
    scheme: default
    primary: 'deep orange'
    accent: 'deep orange'
  language: en
  features:
    - tabs
